name: Nostr
description: Send EVENT to Nostr
inputs:
  relay:
    description: Relay URL `wss://...`
    required: true
  private-key:
    description: Private key `nsec1...` or hex
    required: true
  content:
    description: Content
    required: true
runs:
  using: node16
  main: dist/index.js
