name: Nostr action
description: Send EVENT to Nostr
branding:
  icon: message-circle
  color: purple
inputs:
  relay:
    description: Relay URL `wss://...`
    required: true
  private-key:
    description: Private key hex
    required: true
  content:
    description: Content
    required: true
runs:
  using: node16
  main: dist/index.js
