name: Nostr action
description: Send EVENT to Nostr
branding:
  icon: message-circle
  color: purple
inputs:
  relays:
    description: Relay URLs `wss://...` (separated by `\n`)
    required: true
  private-key:
    description: Private key (nsec or hex)
    required: true
  content:
    description: Content
    required: true
runs:
  using: node16
  main: dist/index.js
