name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
        env:
          NOSTR_RELAYS: ${{ vars.NOSTR_RELAYS }}
          NOSTR_PRIVATE_KEY: ${{ secrets.NOSTR_PRIVATE_KEY }}

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        relays: |
          ${{ vars.NOSTR_RELAYS }}
        private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
        content: |
          test
          https://github.com/snow-actions/nostr
